{% set version = "2.15.05" %}

package:
  name: nasm
  version: {{ version }}

source:
  fn: nasm-{{ version }}.tar.gz
  url: https://www.nasm.us/pub/nasm/releasebuilds/{{ version }}/nasm-{{ version }}.tar.gz
  sha256: 9182a118244b058651c576baa9d0366ee05983c4d4ae1d9ddd3236a9f2304997

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - gnuconfig  # [unix]
    - make  # [unix]
    - perl  # [win]
  host:

test:
  commands:
    - nasm -h
    - nasm -version
    - ndisasm -h

about:
  home: http://www.nasm.us
  license: BSD-2-Clause
  license_file: LICENSE
  summary: "Netwide Assembler: an assembler targetting the Intel x86 series of processors."

extra:
  recipe-maintainers:
    - jakirkham
    - rhpvorderman
